### ISSUE TITLE
Task Incomplete Use Case

### ISSUE THREAD

**Issue by Micheal-Nguyen** [CMPUT301W18T05/Taskzilla#28]
Task Requester or Task Provider, not sure. Could be on either end maybe?

**Comment by myapplestory** [comment]
can you elaborate, i dont quite know what this represents

**Comment by Micheal-Nguyen** [comment]
US 07.02.01
As a task requester, I want to set a task with status: assigned to have status: requested, when it is not completed.

I'm thinking, the task provider can set the status from assigned back to requested (allowing for bids again) if they don't like the provider or other reasons such as not finishing the task.

**Comment by wyattp** [comment]
what did we decide on this.
