### ISSUE TITLE
add unit test cases for initial oo design

### ISSUE THREAD

**Issue by wyattp** [CMPUT301W18T05/Taskzilla#32]

**Comment by wyattp** [comment]
added unit test for Task

**Comment by A-Li97** [comment]
Finished EmailAddress unit test case

**Comment by Micheal-Nguyen** [comment]
Finished PhoneNumber unit test case

**Comment by jng3** [comment]
Finished Bid unit test case

**Comment by colinchoix** [comment]
Finished Review and Photo Test Cases

**Comment by myapplestory** [comment]
Finished User class and User test cases
